DISTANCE_THRESHOLD = 2
JUNK_ID = -1

TOMOGRAM_DIMENSION = 100
#TOMOGRAM_DIMENSION = 40
TOMOGRAM_DIMENSIONS_2D = (TOMOGRAM_DIMENSION,TOMOGRAM_DIMENSION,1)
TOMOGRAM_DIMENSIONS_3D = (TOMOGRAM_DIMENSION,TOMOGRAM_DIMENSION,TOMOGRAM_DIMENSION)

TEMPLATE_DIMENSION = 19
#TEMPLATE_DIMENSION = 22
TEMPLATE_DIMENSIONS_2D = (TEMPLATE_DIMENSION,TEMPLATE_DIMENSION,1)
TEMPLATE_DIMENSIONS_3D = (TEMPLATE_DIMENSION,TEMPLATE_DIMENSION,TEMPLATE_DIMENSION)
