DISTANCE_THRESHOLD = 2
JUNK_ID = -1

TOMOGRAM_DIMENSION = 100
TOMOGRAM_DIMENSIONS = (TOMOGRAM_DIMENSION,TOMOGRAM_DIMENSION)
TOMOGRAM_DIMENSIONS_2D = (TOMOGRAM_DIMENSION,TOMOGRAM_DIMENSION,1)
TOMOGRAM_DIMENSIONS_3D = (TOMOGRAM_DIMENSION,TOMOGRAM_DIMENSION,TOMOGRAM_DIMENSION)